apiVersion: v1
kind: Pod
metadata:
  name: twtest
  labels:
    app: lambdacraft
spec:
  restartPolicy: Never
  containers:
  - name: server
    image: us.gcr.io/minecraft-experimentation/lambdacraft-server
    ports:
    - containerPort: 25565
    - containerPort: 25575
    volumeMounts:
      - mountPath: "/data"
        name: lambdacraft-volume
  - name: monitor
    image: us.gcr.io/minecraft-experimentation/lambdacraft-monitor
    env:
    - name: LAMBDACRAFT_HOST
      value: localhost
  volumes:
  - name: lambdacraft-volume
    persistentVolumeClaim:
      claimName: pvc-lambdacraft
