apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: lambdacraft
spec:
  type: NodePort
  selector:
    app: lambdacraft
  ports:
  - port: 25565
    nodePort: 30000
  - port: 25575
    nodePort: 30010
